version: '3'

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    privileged: true
    hostname: gitlab
    environment:
      GITLAB_ROOT_PASSWORD: rootroot
    networks:
      - gitlab
    ports:
      - 80:80
      - 443:443
      - 22:22
      - 5005:5005
    volumes:
      - /data/gitlab/etc:/etc/gitlab
      - /data/gitlab/log:/var/log/gitlab
      - /data/gitlab/data:/var/opt/gitlab
    extra_hosts:
      - host.docker.internal:host-gateway

  gitlab-runner:
    depends_on:
      - gitlab
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    hostname: gitlab-runner
    privileged: true
    networks:
      - gitlab
    ports:
      - 9252:9252
    volumes:
      - /data/gitlab-runner/etc:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  gitlab:
